logo:
  icon: /assets/icon.svg
  title: Stellar
  subtitle: '每个人的独立博客 | Designed by xaoxuu'
menubar:
  items: []
site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  share: [wechat, weibo, email, link]

style:
  border-radius:
    bar: 4px
    card: 4px
    block: 4px